[View in Colaboratory](https://colab.research.google.com/github/NehaAgarwal2598/MLCC_Sessions/blob/master/Neural.ipynb)

In [0]:
import numpy as np
from sklearn import datasets
import pandas as pd
from pandas import DataFrame as df

In [4]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target
X = np.insert(X,X.shape[1],Y,axis=1)
data = pd.DataFrame(X)

data =  data.reindex(np.random.permutation(data.index))
data.head()


0    1    2    3    4
39   5.1  3.4  1.5  0.2  0.0
107  7.3  2.9  6.3  1.8  2.0
21   5.1  3.7  1.5  0.4  0.0
4    5.0  3.6  1.4  0.2  0.0
50   7.0  3.2  4.7  1.4  1.0

In [8]:
features = data.iloc[:,:4]
target = data.iloc[:,4]

target = target.values.reshape((target.shape[0],1))
target_class = np.zeros(shape=(target.shape[0],3))


for i in range(target.shape[0]):
  if target[i]==0:
    target_class[i][0]=1
  elif target[i]==1:
    target_class[i][1]=1
  else :
    target_class[i][2]=1

print(target_class.shape)
print(target.shape)
print(target_class)


(150, 3)
(150, 1)
[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.

In [0]:
def sigmoid(x):
  return 1/(np.exp(-x))

def der_sigmoid(x):
  return (sigmoid(x)*(1-sigmoid(x)))

In [0]:
input_nodes = features.shape[1]
output_nodes = 3
weight_matrix = np.random.uniform(size=(input_nodes, output_nodes))

epoch = 100000
lr = 0.00002                                  

In [0]:
for i in range(epoch):
    output_node_input = features.dot(weight_matrix)
    output = sigmoid(output_node_input)
    
    error = target_class - output
    drv = der_sigmoid(output_node_input)
    delta_weight = error*drv
    
    weight_matrix = weight_matrix + lr*features.T.dot(delta_weight)

In [29]:
final_output = np.array(output)
print(final_output)


output_class = np.zeros(shape=final_output.shape[0])

for i in range(final_output.shape[0]):
  output_class[i] = np.argmax(final_output[i])
  
print(output_class)

#class_diff = output_class - target[:,0]


[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf 

In [31]:
print('Actual Class')
print(target[:,0])
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
print('predicted Class')
print(output_class)

wrong_prediction = np.count_nonzero(class_diff)
N = len(class_diff)
print(class_diff)

simple_accuracy = 100*(N-wrong_prediction)/N
print("Accuracy :- "+str(simple_accuracy)+ '%')

Actual Class
[0. 2. 0. 0. 1. 2. 2. 0. 2. 2. 1. 0. 1. 1. 2. 0. 2. 1. 0. 2. 2. 2. 1. 0.
 2. 2. 0. 1. 0. 2. 1. 2. 1. 1. 1. 1. 2. 1. 0. 2. 1. 0. 0. 0. 1. 0. 1. 2.
 2. 1. 1. 2. 1. 1. 2. 1. 0. 2. 1. 1. 1. 0. 2. 1. 2. 1. 0. 0. 1. 2. 1. 2.
 2. 0. 2. 0. 2. 0. 1. 1. 0. 2. 2. 2. 0. 1. 2. 0. 2. 0. 1. 2. 2. 1. 0. 1.
 2. 0. 2. 0. 2. 1. 1. 1. 1. 0. 0. 1. 2. 0. 0. 0. 2. 0. 1. 2. 0. 1. 0. 1.
 1. 0. 1. 0. 0. 2. 0. 0. 2. 1. 2. 0. 1. 2. 2. 0. 1. 2. 0. 1. 2. 2. 0. 1.
 0. 0. 1. 0. 2. 0.]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
predicted Class
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[ 0. -2.  0.  0. -

TypeError: ignored