[View in Colaboratory](https://colab.research.google.com/github/NehaAgarwal2598/MLCC_Sessions/blob/master/NeuralNetwork.ipynb)

In [0]:
import numpy as np
from sklearn import datasets
import pandas as pd
from pandas import DataFrame as df

In [2]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target
X = np.insert(X, X.shape[1], Y, axis = 1)
data = pd.DataFrame(X)

data = data.reindex(np.random.permutation(data.index))
data.head()

0    1    2    3    4
75   6.6  3.0  4.4  1.4  1.0
133  6.3  2.8  5.1  1.5  2.0
85   6.0  3.4  4.5  1.6  1.0
57   4.9  2.4  3.3  1.0  1.0
49   5.0  3.3  1.4  0.2  0.0

In [0]:
features = data.iloc[:,:4]
target = data.iloc[:,4]

target = target.values.reshape(target.shape[0],1)
target_class = np.zeros(shape = (target.shape[0],3))

for i in range(target.shape[0]):
    if target[i] == 0:
        target_class[i][0] = 1
    elif target[i] == 1:
        target_class[i][1] = 1
    else:
        target_class[i][2] = 1
#print(target_class.shape)
#print(target.shape)
#print(target_class)

In [0]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def der_sigmoid(x):
    return (sigmoid(x)*(1-sigmoid(x)))

In [0]:
input_nodes = features.shape[1]
output_nodes = 3

weight_matrix = np.random.uniform(size = (input_nodes, output_nodes))

epoch = 1000000
lr = 0.000000004

In [0]:
for i in range(epoch):
    output_node_input = features.dot(weight_matrix)
    output = sigmoid(output_node_input)
    
    error = target_class - output
    drv = der_sigmoid(output_node_input)
    delta_weight = error*drv
    
    weight_matrix = weight_matrix + lr*features.T.dot(delta_weight)

In [11]:
final_output = np.array(output)
print(final_output)
output_class = np.zeros(shape = final_output.shape[0])
for i in range(final_output.shape[0]):
    output_class[i] = np.argmax(final_output[i])
print(output_class)
class_diff = output_class - target[:,0]

[[9.37607108e-03 6.06862565e-02 1.78466470e-05]
 [7.73049481e-04 8.74470879e-02 2.39865695e-05]
 [7.99019476e-03 7.72569880e-04 2.87705367e-05]
 [3.85589500e-02 6.29039891e-02 2.64936487e-04]
 [9.87435084e-01 8.82699510e-03 2.15228596e-04]
 [1.01065188e-02 2.54791520e-02 6.47030396e-05]
 [8.02610105e-04 2.97230374e-02 2.78402220e-05]
 [9.78416133e-01 3.38275004e-02 2.63803150e-04]
 [1.33120247e-02 7.26192054e-03 6.47062025e-05]
 [9.78416133e-01 3.38275004e-02 2.63803150e-04]
 [1.17055173e-02 4.68516211e-02 1.48784347e-05]
 [9.85140067e-01 1.22648377e-03 3.32465798e-04]
 [9.81479294e-01 5.62578255e-03 3.71411540e-04]
 [9.81094224e-01 1.77020449e-02 1.14478828e-04]
 [9.63653193e-01 3.28126565e-03 1.80562861e-04]
 [3.87840293e-03 1.64587516e-02 3.85521411e-05]
 [9.76215605e-01 5.15460951e-04 1.87746822e-04]
 [8.41115972e-05 3.08092943e-03 1.46850424e-05]
 [2.58505612e-04 3.21508500e-02 2.22297634e-05]
 [9.66956869e-01 1.78644753e-02 2.92462993e-04]
 [9.69790999e-04 1.65143100e-03 1.555806

In [12]:
print('Actual Class')
print(target[:,0])
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
print('predicted Class')
print(output_class)

wrong_prediction = np.count_nonzero(class_diff)
N = len(class_diff)
print(class_diff)

simple_accuracy = 100*(N-wrong_prediction)/N
print("Accuracy :- "+str(simple_accuracy)+ '%')

Actual Class
[1. 2. 1. 1. 0. 1. 2. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 2. 2. 0. 2. 1. 1. 2.
 2. 0. 0. 1. 0. 2. 2. 2. 1. 2. 0. 1. 0. 0. 2. 1. 2. 1. 1. 1. 0. 2. 0. 2.
 2. 0. 0. 2. 0. 1. 0. 1. 2. 0. 0. 2. 0. 0. 2. 0. 1. 2. 2. 2. 0. 2. 2. 1.
 1. 2. 1. 2. 1. 2. 0. 2. 2. 1. 0. 2. 0. 0. 0. 1. 1. 0. 0. 0. 2. 0. 1. 1.
 2. 0. 1. 2. 2. 1. 0. 1. 2. 2. 1. 1. 2. 2. 1. 1. 2. 0. 1. 1. 2. 1. 0. 1.
 1. 0. 0. 1. 1. 0. 0. 2. 0. 2. 0. 2. 1. 1. 1. 2. 2. 0. 2. 1. 0. 2. 0. 1.
 0. 1. 2. 1. 2. 1.]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
predicted Class
[1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1.
 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1.
 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1.
 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1.
 0. 1. 1. 1. 1. 0.]
[ 0. -1. -1.  0.  